### PR TITLE
Use custom logIndex for evm events

### PR DESCRIPTION
**Pull request by ziscky**
https://app.clickup.com/t/8694npryf

In EVM events the `LogIndex` is only unique within the same `TransactionIndex`.

:link: [zboto Link](https://app.clickup.com/t/8694nreyq)

### CODE REVIEW

**Review by emmanuelm41 — COMMENTED** [review]
My only concern here is if the events are ordered by tx hash or not... are we sure about that?

**Comment by ziscky** [comment]
> My only concern here is if the events are ordered by tx hash or not... are we sure about that?

I thought this would be the case as in the NativeLogs, but I guess we can sort them first

**Comment by emmanuelm41** [comment]
I think the same, but please, let's be sure about that! We could order by transactionIndex, and logIndex, so that we are sure things are correctly ordered

**Review by emmanuelm41 — APPROVED** [review]

**Comment by emmanuelm41** [comment]
We need to fix CI first!

**Pull request merged**
